// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const DATABASE_URL_ENV_NAME = "DATABASE_POOLER_URL";
const DATABASE_PASSWORD_ENV_NAME = "DATABASE_PASSWORD";

const rawDatabaseUrl = process.env[DATABASE_URL_ENV_NAME];
const rawDatabasePassword = process.env[DATABASE_PASSWORD_ENV_NAME];

const databasePasswordExpression = `$\{${DATABASE_PASSWORD_ENV_NAME}}`;

const databaseUrl =
  !!rawDatabasePassword && rawDatabaseUrl?.includes(databasePasswordExpression)
    ? rawDatabaseUrl.replace(databasePasswordExpression, rawDatabasePassword)
    : rawDatabaseUrl;

export default defineConfig({
  schema: "prisma/schema/",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
